# https://github.com/googleapis/release-please-action?tab=readme-ov-file
name: Prepare Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node

  build:
    permissions:
      contents: write
    name: Upload tarball
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Compile
        run: npm run build-dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "defaulted-*.tgz"
          tag: ${{ needs.release-please.outputs.tag_name }}
